### ISSUE TITLE
Possible optimization on Contract viewing page

### ISSUE THREAD

**Issue by javaadpatel** [openlawteam/openlaw-website#106]
Hi, I'm not sure if its correct in saying this as I'm still reading through the API docs. I noticed that on the page that displays the contract (https://app.openlaw.io/contract/{contractId}), the call `/contract/raw/?contractId` is repeatedly made, even though the contract is already signed. I guess it makes sense to keep polling this while there is no signature so the UI is immediately updated once there is a signature, but after a valid signature is there then it doesn't seem like the data changes?

![image](https://user-images.githubusercontent.com/22832462/67239105-c4ecf200-f44e-11e9-8fee-27b3d17d0844.png)

**Comment by jtrein** [comment]
Hi, @javaadpatel thanks for reporting this! Looking only at this GH issue, I tend to agree with you. I haven't looked at the underlying causes, just yet. We eventually want to move things like this to Server-sent Events, or possibly Web Sockets.

---

Also, we need to do better on routing support issues. Here's the correct places for most OpenLaw bugs:

- OpenLaw web app: https://github.com/openlawteam/openlaw-issue-tracker/issues
- OpenLaw web site (marketing & info): https://github.com/openlawteam/openlaw-website/issues
- OpenLaw Core ("under the hood"): https://github.com/openlawteam/openlaw-core/issues
- OpenLaw Client (JS interface to Core & helper lib for API calls): https://github.com/openlawteam/openlaw-client/issues

Most times I also have to guess between App/Core/Client 🧐!  I'll move this to the app's issue tracker for you!

**Comment by jtrein** [comment]
Moved: https://github.com/openlawteam/openlaw-issue-tracker/issues/23
