### ISSUE TITLE
Change proxy address to website; change Netlify site name

### ISSUE THREAD

**Issue by jtrein** [openlawteam/openlaw-website#48]
I'll be away for part of the week this week, so the only window I am guaranteed is my Monday or Tuesday at night. If this doesn't get done before Wednesday, @mroth could you help @mingfang if you're not too busy?

---

* New proxied address: `https://openlaw-website.netlify.com`
* New Netlify site name: `openlaw-website`

From @mroth:

> We should probably consider renaming the netlify project from `openlaw-beta` to something else since it’s no longer in beta, just to avoid confusing ourselves, and for public community PRs.  `openlaw-website` to match the github repo?  (cc Jacqueline Outka Jeremiah Trein and Ming Fang — there’s a bit of a chicken and egg coordination here, since I believe the AWS nginx proxy Ming Fang refers to the project name URL, so we’d have to coordinate changing it at both places to avoid breaking things I think?)

**Comment by mingfang** [comment]
Getting a 404

```
curl -I https://openlaw-website.netlify.com
HTTP/2 404 
cache-control: max-age=30, public
content-length: 0
content-type: text/html; charset=utf-8
date: Mon, 17 Sep 2018 14:48:05 GMT
x-frame-options: ALLOWALL
x-request-id: 32476cd1-b92a-45ff-8a01-1c9455400535
x-runtime: 0.006389
age: 0
server: Netlify
x-nf-request-id: 068b72ad-7cdc-4f7f-ab0e-a3c00f0f0303-13478884
```

**Comment by mroth** [comment]
> Getting a 404

@mingfang we haven't switched it over since it seems we will need to coordinate the timing.  want to just grab me or @jtrein on Slack when a convenient time for you? I'll be on East Coast time today/tomorrow before hopping on a plane Wednesday, @jtrein is Nepal time until then.

**Comment by mingfang** [comment]
You can make the change yourself by editing lines 15 and 16 here https://github.com/openlawteam/openlaw-infra/blob/17be2336e9d795833b480648a8e465303b415dd8/prod/services/instances/openlaw.yml#L15

**Comment by mroth** [comment]
@mingfang I see, are and that will take effect upon being pushed to master?

**Comment by mingfang** [comment]
Jenkins will deploy the changes within 2 minutes

**Comment by mroth** [comment]
Got it, thanks!

**Comment by mroth** [comment]
All seems good! Thanks @mingfang.
