### ISSUE TITLE
Netlify - clear build cache

### ISSUE THREAD

**Issue by nostalgic** [openlawteam/openlaw-website#5]
whoever has the netlify access will need to clear the build cache on deploy:
In deploys tab, click trigger deploy and check "clear build cache"

Looks like stylesheet isn't being either compiled or copied over to static on build or deploy to Netlify.
Suggested solutions were do remove package-lock.json folder and "clear build cache" flag on Netlify

**Comment by mroth** [comment]
@nostalgic me, jeremiah and jacqueline have access.  I'll clear it now.  (My understanding is normally we won't have to do this, since it detects any committed changes to package.json or the lock file?)

**Comment by mroth** [comment]
Complete. √ LMK if it fixes the issue.

**Comment by nostalgic** [comment]
Unfortunately this didn't fix the issue - could be a problem in `gatsby build`. Looking at the Netlify site, seems classes inherited from the CSS aren't being recognized. 

Maybe @jtrein can peek into this? He set up the project initially and may have more insight into how the production build is being handled.

**Comment by jtrein** [comment]
I'll take a look! It's working locally, but not on deploy?
