### ISSUE TITLE
OG Tags for What Displays When Sharing

### ISSUE THREAD

**Issue by atgrif** [openlawteam/openlaw-website#61]
Problem/Enhancement
We need to set our OpenLaw OG tags so we control what images and content show up when people share our site on social media. We don't have any of these properties currently. 

Assessment
https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fopenlaw.io

Pages
All pages not behind login:
- https://openlaw.io/
- https://openlaw.io/about
- https://openlaw.io/private-instances
- https://app.openlaw.io/login
- https://app.openlaw.io/signup
- https://openlaw.io/faq/

Detail
og:url - URL for the specific page
og:type - website
og:title - corresponding page title
og:image - OpenLaw logo
og:description - We are home to a passionate group of people, technologists, and dreamers committed to rebuilding the legal industry.
fb:app_id - (must create one: https://stackoverflow.com/questions/8845082/getting-fb-app-id-from-a-fb-page)

Acceptance Criteria
- When the user shares a page from openlaw.io, the title, description, and thumbnail display what we set in the OG tags.
- When a user who is viewing the post on the corresponding social media site clicks on the link, they are taken to the correct corresponding page.

Special QA Instructions
- Need to be able to test via a social media network or chat platform like Slack

Related Links
https://www.optimizesmart.com/how-to-use-open-graph-protocol/
https://api.slack.com/docs/message-link-unfurling#classic_unfurling

**Comment by atgrif** [comment]
Github doesn't want to let me attach an SVG. Can share when you need the logo.

**Comment by jtrein** [comment]
[logos.zip](https://github.com/openlawteam/openlaw-website/files/2413650/logos.zip)

Here's some I zipped-up. Hopefully, this helps!

**Comment by rjfranco** [comment]
(reopened because the other pr needs a merge too)

**Comment by outkaj** [comment]
good call, I am surprised that got closed automatically

**Comment by jtrein** [comment]
@rjfranco For the markdown pages `/private-instances`, `/about`, `/faq` I think we will have to use the frontmatter in the YAML header to insert some meta description (etc.) via GraphQL. Not a bad thing. Makes it easy for anyone to update the text, and meta.

**Comment by rjfranco** [comment]
@jtrein Aside from the title and url that stuff is the same across the site. We can always add that later if we decide to get more granular on the meta data ( but for now it seems, that won't be necessary )

**Comment by jtrein** [comment]
Is this one merged and done?

**Comment by rjfranco** [comment]
@jtrein Yeessish? So the ticket covers most views but docs is also a publicly exposed resource, we should also add OG tags there, I started going down that process but got distracted by other priorities. But it may be best to do that as a separate task seeing as how the endpoints listed in this ticket are covered. I'll verify with @atgrif though

**Comment by jtrein** [comment]
Yeah, since you've covered your bases in this context, I think maybe open a similar issue on: https://github.com/openlawteam/docs/issues/new

@atgrif is that cool with you?

**Comment by atgrif** [comment]
Cool with me :)
