### ISSUE TITLE
About Page - Text does not follow page margins in smaller breakpoints

### ISSUE THREAD

**Issue by atgrif** [openlawteam/openlaw-website#80]
Problem
Too much space at top of page and margins are too wide.

Screenshot
![img-3099](https://user-images.githubusercontent.com/25940861/51058452-c97aa500-15b6-11e9-9387-551fc81e19c8.PNG)

Page
About - https://openlaw.io/about

Acceptance Criteria
- [ ] Spacing at top is not excessive
- [ ] Margins match the header
- [ ] Resize images for the smaller breakpoints so they don't break the page

**Comment by sophiacodes** [comment]
Fixed in PR https://github.com/openlawteam/openlaw-website/pull/86

**Comment by sophiacodes** [comment]
@atgrif let me know if the fix in https://github.com/openlawteam/openlaw-website/pull/86 is sufficient for this, or if you still want the image removed.

**Comment by atgrif** [comment]
Looks good!
