### ISSUE TITLE
Private Instances Landing - Too much space at top of page and margins are too wide.

### ISSUE THREAD

**Issue by atgrif** [openlawteam/openlaw-website#81]
Problem
Too much space at top of page and margins are too wide.

Screenshot
![img-3100](https://user-images.githubusercontent.com/25940861/51065938-8b40ae00-15d5-11e9-909a-08f15a4c49a5.PNG)

Page
Request Private Instance Landing - https://openlaw.io/private-instances

Acceptance Criteria
- [ ] Spacing at top is not excessive
- [ ] Margins match the header

**Comment by sophiacodes** [comment]
Fixed in PR https://github.com/openlawteam/openlaw-website/pull/86

**Comment by atgrif** [comment]
I wasn't specific enough in the description of this ticket. Text on the page should fit within the margins on this page. 
<img width="328" alt="margins" src="https://user-images.githubusercontent.com/25940861/51191984-891b6f80-18b3-11e9-98f8-7d8dc7251930.png">

**Comment by atgrif** [comment]
Looks good.
