### ISSUE TITLE
Frequently Asked Questions - Too much space at top of page and margins are too wide.

### ISSUE THREAD

**Issue by atgrif** [openlawteam/openlaw-website#82]
Problem
Too much space at top of page and margins are too wide.

Screenshot
![img-3101](https://user-images.githubusercontent.com/25940861/51066058-25a0f180-15d6-11e9-8d4e-22cb897b6251.PNG)

Page
FAQ Page - https://openlaw.io/faq

Acceptance Criteria
- [ ] Spacing at top is not excessive
- [ ] Margins match the header

**Comment by sophiacodes** [comment]
Fixed in PR https://github.com/openlawteam/openlaw-website/pull/86

**Comment by atgrif** [comment]
Looks good!
