### ISSUE TITLE
Terms of Use - Too much space at top of page and margins are too wide.

### ISSUE THREAD

**Issue by atgrif** [openlawteam/openlaw-website#83]
Problem
Too much space at top of page and margins are too wide.

Screenshot
![img-3102](https://user-images.githubusercontent.com/25940861/51066194-cbecf700-15d6-11e9-884f-5158890f0794.PNG)

Page
Terms of Use - https://openlaw.io/terms

Acceptance Criteria
- [ ] Spacing at top is not excessive
- [ ] Margins match the header

**Comment by sophiacodes** [comment]
Fixed in PR https://github.com/openlawteam/openlaw-website/pull/86

**Comment by atgrif** [comment]
I wasn't specific enough in the original description. Text on page should fit within the margins as shown below.
<img width="328" alt="margins" src="https://user-images.githubusercontent.com/25940861/51192052-b700b400-18b3-11e9-9f0f-305bb55abaeb.png">

**Comment by atgrif** [comment]
Looks good.
