### ISSUE TITLE
Privacy Policy - Table breaking margins

### ISSUE THREAD

**Issue by atgrif** [openlawteam/openlaw-website#85]
Problem
Table within the privacy policy is causing things to go out of margins

Screenshot
![privacy_table](https://user-images.githubusercontent.com/25940861/51066940-af06f280-15db-11e9-886d-c4f37106c90e.PNG)

Page 
Privacy. Policy -  https://openlaw.io/privacy

Acceptance Criteria 
- [ ] In small breakpoint, table is scrollable from left to right so it doesn't go out of margins.

**Comment by sophiacodes** [comment]
Fixed in PR https://github.com/openlawteam/openlaw/pull/new/issue-1834

**Comment by atgrif** [comment]
Looks good.
